/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import Employee_Details.EmProfile;
import java.util.ArrayList;




public class CreateProfileJPanel extends javax.swing.JPanel {
    
    static Boolean RUN_ONCE = false; 
    static ArrayList<EmProfile> emp1=new ArrayList<EmProfile>();
    EmProfile emp2=new EmProfile();
    /**
     * Creates new form CreateProfileJPanel
     * @param emp
     */
    
    
    public CreateProfileJPanel() {
    }

    public CreateProfileJPanel(EmProfile emp) {
        initComponents();
        /* Setting the value of Textfield - To be used in validate function*/
        textforname.setName("Name");
        textempid.setName("empid");
        textforage.setName("age");
        textgender.setName("gender");
        textfordate.setName("sdate");
        textforlevel.setName("level");
        textforteaminfo.setName("teaminfo");
        textpositiontitle.setName("postitle");
        textforphonenumber.setName("cellno");
        textforemail.setName("email");
        //emp1.add(emp);
    }
    
    /*validateData() - Takes a JComponent as input - Perform validation if data received is valid*/
    public boolean validateData(JComponent input) {
        String name = input.getName();
        String errorMsg="";
        boolean raiseError = false;
        String text = ((JTextField) input).getText().trim();
        if (text == null || text.isEmpty()) {
            raiseError = true;
            errorMsg = String.format("Please enter a value. The value for %s cannot be empty", name);

        }
        else{
            switch (name) {
                case "Name":
                    if(!text.matches("^[a-zA-z]+$")){
                        raiseError = true;
                        errorMsg = String.format("Please enter valid values for %s", name);
                    }   break;
                case "cellno":
                    if(!text.matches("^[0-9]{10}")){
                        raiseError = true;
                        errorMsg = String.format("Please enter a valid %s", name);
                    }   break;
                case "sdate":
                    if(!text.matches("^((0[0-9]||1[0-2])/[0-2][0-9]||3[0-1])/([0-9][0-9])?[0-9][0-9]$")){
                        raiseError = true;
                        errorMsg = String.format("Please enter a valid %s with the format MM/DD/YYYY", name);
                    }   break;
                
                case "EmailAddress":
                    if(!text.matches("^(.+)@(.+)$")){
                        raiseError = true;
                        errorMsg = String.format("Please enter a valid %s", name);
                    }   break;
                case "empid":
                   if(!emp1.isEmpty()) {
                       for (EmProfile emp3 : emp1) {
                           if (String.valueOf(emp3.getEmpid()).equals(text)) {
                               raiseError = true;
                               errorMsg = "Employee ID already exists";
                               break;
                           }
                     }
        }
                default:
                    break;
            }
        }
        if (raiseError){
            JOptionPane.showMessageDialog(this, errorMsg);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        buttonforsaving = new javax.swing.JButton();
        textforage = new javax.swing.JTextField();
        textfordate = new javax.swing.JTextField();
        lableforposition = new javax.swing.JLabel();
        lableofcontactinfo = new javax.swing.JLabel();
        textforname = new javax.swing.JTextField();
        textempid = new javax.swing.JTextField();
        textgender = new javax.swing.JTextField();
        lableforteaminfo = new javax.swing.JLabel();
        textforemail = new javax.swing.JTextField();
        lablefordate = new javax.swing.JLabel();
        lableforage = new javax.swing.JLabel();
        lableforgender = new javax.swing.JLabel();
        textforlevel = new javax.swing.JTextField();
        textpositiontitle = new javax.swing.JTextField();
        lableforemail = new javax.swing.JLabel();
        lableforempid = new javax.swing.JLabel();
        labelforphoto = new javax.swing.JLabel();
        labelforname = new javax.swing.JLabel();
        textforphonenumber = new javax.swing.JTextField();
        labelforphonenumber = new javax.swing.JLabel();
        lableforlevel = new javax.swing.JLabel();
        textforteaminfo = new javax.swing.JTextField();
        bottonforupload = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 204));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(800, 800));

        lblTitle.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Employee");

        buttonforsaving.setBackground(new java.awt.Color(255, 204, 0));
        buttonforsaving.setText("Save");
        buttonforsaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonforsavingActionPerformed(evt);
            }
        });

        textforage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textforageActionPerformed(evt);
            }
        });

        textfordate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfordateActionPerformed(evt);
            }
        });

        lableforposition.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableforposition.setText("Position Title");

        lableofcontactinfo.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableofcontactinfo.setText("Contact Info");

        textforname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfornameActionPerformed(evt);
            }
        });

        textempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textempidActionPerformed(evt);
            }
        });

        textgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textgenderActionPerformed(evt);
            }
        });

        lableforteaminfo.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableforteaminfo.setText("TeamInfo");

        textforemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textforemailActionPerformed(evt);
            }
        });

        lablefordate.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lablefordate.setText("Start Date");

        lableforage.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableforage.setText("Age");

        lableforgender.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableforgender.setText("Gender");

        textforlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textforlevelActionPerformed(evt);
            }
        });

        textpositiontitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpositiontitleActionPerformed(evt);
            }
        });

        lableforemail.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableforemail.setText("Email");

        lableforempid.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableforempid.setText("Employee ID");

        labelforphoto.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        labelforphoto.setText("Photo:");

        labelforname.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        labelforname.setText("Name:");

        textforphonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textforphonenumberActionPerformed(evt);
            }
        });

        labelforphonenumber.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        labelforphonenumber.setText("Cell no");

        lableforlevel.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        lableforlevel.setText("Level");

        textforteaminfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textforteaminfoActionPerformed(evt);
            }
        });

        bottonforupload.setText("Upload");
        bottonforupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonforuploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelforname)
                                        .addGap(37, 37, 37)
                                        .addComponent(textforname, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lablefordate)
                                            .addComponent(lableforteaminfo))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textforteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textfordate, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lableforgender)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lableforlevel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textforlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lableforposition)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addComponent(textpositiontitle, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lableforage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textforage, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lableforempid)
                                .addGap(7, 7, 7)
                                .addComponent(textempid, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textgender, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelforphoto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelforphonenumber)
                                    .addGap(41, 41, 41)
                                    .addComponent(textforphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lableforemail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textforemail, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bottonforupload)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lableofcontactinfo)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(buttonforsaving, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelforname)
                    .addComponent(textforname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableforage)
                    .addComponent(textforage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableforgender)
                    .addComponent(lableforempid)
                    .addComponent(textempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfordate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lablefordate)
                    .addComponent(lableforlevel)
                    .addComponent(textforlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textforteaminfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lableforposition)
                        .addComponent(textpositiontitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lableforteaminfo))
                .addGap(32, 32, 32)
                .addComponent(lableofcontactinfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelforphonenumber)
                    .addComponent(textforphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableforemail)
                    .addComponent(textforemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottonforupload)
                    .addComponent(labelforphoto))
                .addGap(38, 38, 38)
                .addComponent(buttonforsaving, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonforsavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonforsavingActionPerformed
        JTextField[] VARIABLE_CONSTANTS = {textforname,textempid,textforage,textgender,textfordate,textforlevel,textforteaminfo,textpositiontitle,textforphonenumber,textforemail};
        boolean validated = false;
        for(JTextField field: VARIABLE_CONSTANTS){
            if(!validateData(field)){
                validated = false;
                break;
            }
            else{
                validated = true;
                System.out.println("Validated");
            }
        }
        if(validated){
            if(!RUN_ONCE){
                emp1.clear();
                RUN_ONCE = true;
            }
            // EmProfile emp2=new EmProfile();
            emp2.setName(textforname.getText());
            emp2.setEmpid(textempid.getText());
            emp2.setAge(textforage.getText());
            emp2.setGender(textgender.getText());
            emp2.setStartdate(textfordate.getText());
            emp2.setLevel(textforlevel.getText());
            emp2.setTeaminfo(textforteaminfo.getText());
            emp2.setPositiontitle(textpositiontitle.getText());
            emp2.setCellno(textforphonenumber.getText());
            emp2.setEmail(textforemail.getText());
            System.out.println(emp1.size());
            emp1.add(emp2);
            
            JOptionPane.showMessageDialog(this,"Employee Profile Successful");
            System.out.println(emp1.size());
            
        }
    }//GEN-LAST:event_buttonforsavingActionPerformed

    private void textforageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textforageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textforageActionPerformed

    private void textfordateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfordateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfordateActionPerformed

    private void textfornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfornameActionPerformed

    private void textempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textempidActionPerformed

    private void textgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textgenderActionPerformed

    private void textforemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textforemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textforemailActionPerformed

    private void textforlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textforlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textforlevelActionPerformed

    private void textpositiontitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpositiontitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpositiontitleActionPerformed

    private void textforphonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textforphonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textforphonenumberActionPerformed

    private void textforteaminfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textforteaminfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textforteaminfoActionPerformed
    
    public static void setArrayLst(ArrayList<EmProfile> empList){
        emp1 = empList;
    }
    private void bottonforuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonforuploadActionPerformed
        
        JFileChooser fileUploader = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "JPG & GIF Images", "jpg", "gif");
        fileUploader.setFileFilter(filter);
        fileUploader.setDialogTitle("Choose Your Photo");
        fileUploader.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnval = fileUploader.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION)
        {
            File uploadedFile = fileUploader.getSelectedFile();
            BufferedImage bufferedImageObj;
            try {
                bufferedImageObj = ImageIO.read(uploadedFile);
                ByteArrayOutputStream byteArrayOs = new ByteArrayOutputStream();
                ImageIO.write(bufferedImageObj, "jpg", byteArrayOs);
                byte[] photoBytes = byteArrayOs.toByteArray();
                emp2.setPhoto(photoBytes);
                emp1.add(emp2);
                JOptionPane.showMessageDialog(fileUploader, "Photo Uploaded Successfully");
            } catch(IOException e) {
               e.printStackTrace();
               JOptionPane.showMessageDialog(fileUploader, "Error while uploading Photo");
            }
        }
    
        
    }//GEN-LAST:event_bottonforuploadActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonforupload;
    private javax.swing.JButton buttonforsaving;
    private javax.swing.JLabel labelforname;
    private javax.swing.JLabel labelforphonenumber;
    private javax.swing.JLabel labelforphoto;
    private javax.swing.JLabel lableforage;
    private javax.swing.JLabel lablefordate;
    private javax.swing.JLabel lableforemail;
    private javax.swing.JLabel lableforempid;
    private javax.swing.JLabel lableforgender;
    private javax.swing.JLabel lableforlevel;
    private javax.swing.JLabel lableforposition;
    private javax.swing.JLabel lableforteaminfo;
    private javax.swing.JLabel lableofcontactinfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField textempid;
    private javax.swing.JTextField textforage;
    private javax.swing.JTextField textfordate;
    private javax.swing.JTextField textforemail;
    private javax.swing.JTextField textforlevel;
    private javax.swing.JTextField textforname;
    private javax.swing.JTextField textforphonenumber;
    private javax.swing.JTextField textforteaminfo;
    private javax.swing.JTextField textgender;
    private javax.swing.JTextField textpositiontitle;
    // End of variables declaration//GEN-END:variables
}


