/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Employee_Details.EmProfile;
import javax.swing.JOptionPane;
import static ui.CreateProfileJPanel.emp1;

/**
 *
 * @author sreej
 */
public class DeleteJPanel extends javax.swing.JPanel {
EmProfile emp4=new EmProfile();
    /**
     * Creates new form DeleteJPanel
     */
    
    DeleteJPanel(EmProfile emp) {
        initComponents();
     this.emp4=emp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbldelete = new javax.swing.JLabel();
        lblempid = new javax.swing.JLabel();
        txtdempid = new javax.swing.JTextField();
        btndelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 204));

        lbldelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbldelete.setText("Delete Employee");

        lblempid.setText("EmpID");

        txtdempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdempidActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 255, 51));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btndelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblempid)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdempid, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbldelete)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblempid))
                .addGap(18, 18, 18)
                .addComponent(btndelete)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdempidActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        //String raise="";
        //String del=txtdempid.getText();
       //if(emp1.contains(txtdempid.getText()))
        for(EmProfile emp:emp1){
            if(emp.getEmpid().equals(txtdempid.getText())){
               
                emp1.remove(emp);
                 JOptionPane.showMessageDialog(this,"Employee Deleted");
                 //System.out.println(emp1.size());
                break;
            }
        }
       
        for(EmProfile emp:emp1){
            if(!emp.getEmpid().equals(txtdempid.getText())){
            
                JOptionPane.showMessageDialog(this,"Employee Does not exist");
                break;
            }
                        
            }
     
        

        
    }//GEN-LAST:event_btndeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel lbldelete;
    private javax.swing.JLabel lblempid;
    private javax.swing.JTextField txtdempid;
    // End of variables declaration//GEN-END:variables
}
